- hosts: local
  user: cloud
  sudo: yes

  tasks:
    - name: apt cache is up-to-date
      apt:
        update_cache=yes
        cache_valid_time=1

    - name: system is up-to-date
      apt:
        upgrade=full

    - name: packages installed
      apt:
        pkg="{{ item }}"
        state=present
      with_items:
        - apache2
        - php5
      notify: start apache2

    - name: default sh is bash
      file:
        src=/bin/bash
        dest=/bin/sh
        state=link

  handlers:
    - name: start jenkins
      service:
        name=jenkins
        state=restarted
        enabled=yes
        
    - name: unzip packer
      unarchive:
        dest=/usr/local/bin
        src=/tmp/packer.zip
        copy=no
        owner=root
        group=staff
        mode=0755
