- hosts: local
  user: cloud
  sudo: yes

  tasks:
    - name: apt cache is up-to-date
      apt:
        update_cache=yes
        cache_valid_time=1

    - name: system is up-to-date
      apt:
        upgrade=full

    - name: packages installed
      apt:
        pkg="{{ item }}"
        state=present
      with_items:
        - apache2
        - php5
      notify: start apache
      
    - git: 
       repo=https://github.com/aurelienmaury/cw-bundle-lamp.git
       dest=/var/www/php
       
    - copy:
       src=lamp.conf
       dest=/etc/apache2/sites-available/
       owner=root
       group=root
       notify: enable apache site

    - name: common aliases
      copy:
        dest=/etc/profile.d/aliases.sh
        content="alias ll=\"ls -aul\""
        owner=root
        group=root
        mode=0644

    - name: default sh is bash
      file:
        dest=/bin/bash
        src=/bin/sh
        state=link

  handlers:
    - name: restart apache
      service:
        name=apache2
        state=restarted
        
    - name: enable apache site
      shell: /usr/sbin/a2dissite 000-default && /usr/sbin/a2ensite lamp
      notify: restart apache
